language: node_js
node_js:
  - "4"
addons:
  firefox: "51.0"
install:
  - npm install
  - npm run bundle
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start