language: node_js
node_js:
  - "6"
env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
install:
  - npm install
  - npm run lib
  - npm run bundle
#before_script:
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"
#  - sleep 3 # give xvfb some time to start